### ISSUE TITLE
Migration Assistant for Microsoft DLP v1.1 not starting

### ISSUE THREAD

**Issue by Christiaan1986** [OfficeDev/MAMD#11]
We tried to run the Migration Assistant for Microsoft DLP v1.1 MSI, but after finishing the installation we can't seem to start to tool. Windows (10/11) doesn't seems to react at all when trying to run the tool. We expect Windows is starting a GUI of the tooling as described in the manual:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/109805190/180444725-f499ac54-255d-45d6-bef2-3c431e19967b.png">
Is there something wrong with the installation or are we missing something here?

**Comment by snehakishore21** [comment]
@Christiaan1986 Can you share the log files found here 'C:\Users\<UserName>\AppData\Local\Temp\MigrationAssistantforMicrosoftDLP\Logs'

Can you please let us know if you were able to run the previous versions?

Please share the event logs as well:
After running the exe, open the event viewer and check for this: (Event viewer-> Windows logs-> Application)
Check if there is any log related to the MigrationAssistantforMicrosoftDLP tool and please share the details.
(Image for reference)
![image](https://user-images.githubusercontent.com/69503744/187840727-52d7c3c8-8397-42c8-8881-a3369478505a.png)

**Comment by Christiaan1986** [comment]
@snehakishore21 thanks for your reply, it seems the log file location isn't available on my machine? Maybe there is a different location? Below I shared the "Application Windows log files". Unfortunately this is the first version we try to to run, so don't know about any previous versions. Should you need more information, pls let me know!
<img width="775" alt="image" src="https://user-images.githubusercontent.com/109805190/188857094-6b87da85-6d56-4b50-966a-b4e90b64185c.png">
<img width="775" alt="image" src="https://user-images.githubusercontent.com/109805190/188857149-63da17d5-0c9f-42dd-889a-7693c1ed348c.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/109805190/188857217-527077db-c279-4870-a5a8-05c54497cd93.png">
<img width="751" alt="image" src="https://user-images.githubusercontent.com/109805190/188857259-925da84e-b759-4e09-b134-a13458aeaf2e.png">

**Comment by rm41** [comment]
I got the same issue.  I tried v1.1 and then v1.0 same result.  double click on the migrator and no pop up window as above.  I follow the event log as instructed and see this error.  Any help on what to do next?

![image](https://user-images.githubusercontent.com/10037422/200380870-727caae7-9976-4a76-b3b1-abfd15ece120.png)

**Comment by snehakishore21** [comment]
Please try the following troubleshooting steps:

Open command prompt as administrator and run the following command:
reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /freg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /freg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /freg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
Restart and try opening the exe again.

**Comment by rm41** [comment]
***@***.***

Time Off: Oct 26 AM,  Nov 21-26, Dec 17-31

***@***.***
______________________________________________________________________________
Ruel Mendoza | Vice President | Data Protection Engineering and Architecture
Mobile: (630) 201-2984 | Office: (630) 663-6274 | ***@***.******@***.***>

CONFIDENTIALITY NOTICE: This communication is confidential, may be privileged and is meant only for the intended recipient. If you are not the intended recipient, please notify the sender ASAP and delete this message from your system.
NTAC:3NS-20




From: snehakishore21 ***@***.***>
Sent: Monday, November 7, 2022 11:58 AM
To: OfficeDev/MAMD ***@***.***>
Cc: Ruel L Mendoza ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [OfficeDev/MAMD] Migration Assistant for Microsoft DLP v1.1 not starting (Issue #11)

This email originated from outside the organization. Do not click links or open attachments unless you have verified this email is legitimate.


Please try the following troubleshooting steps:

Open command prompt as administrator and run the following command:
reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /freg ADD "HKLM\Software\Microsoft\StrongName\Verification*," /freg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /freg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification*," /f
Restart and try opening the exe again.

-
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2FMAMD%2Fissues%2F11%23issuecomment-1305982087&data=05%7C01%7Crm41%40ntrs.com%7Cd2fd0a20f1af4aebb2a508dac0e9992c%7C2434528d4270497781dda6308c1761a3%7C0%7C0%7C638034406780399312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MOWIFApmjgAE1t9dxwQrXKozNlD1fxDj1Oj3Ko0ZC30%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACMSRLWA6F7ZMPZXNDXF7TDWHE7JZANCNFSM54LNWW7Q&data=05%7C01%7Crm41%40ntrs.com%7Cd2fd0a20f1af4aebb2a508dac0e9992c%7C2434528d4270497781dda6308c1761a3%7C0%7C0%7C638034406780399312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L4wCo8uxl5FwSnE1KeuIgJnQW9kFWlm4zMvv%2F9NC8zc%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>


NTAC:3NS-20

**Comment by rm41** [comment]
![image](https://user-images.githubusercontent.com/10037422/200392211-8a0556fb-36c1-4fce-8587-17e6fe356004.png)

**Comment by snehakishore21** [comment]
> ![image](https://user-images.githubusercontent.com/10037422/200392211-8a0556fb-36c1-4fce-8587-17e6fe356004.png)

@rm41 Updated the comment. Please run those 4 cmds in cmd prompt.

**Comment by snehakishore21** [comment]
@rm41 @Christiaan1986 
We have released a new version of the Migration tool last week and recruiting few customers for Private preview. If you are interested, please email to [dlpmigrations@microsoft](mailto:dlpmigrations@microsoft).
